-- ==========================================
-- FINAL DATABASE SETUP FOR SKIEZ PHARMA
-- ==========================================
-- This script sets up all tables, RLS policies, and Storage buckets.
-- Use this in the Supabase SQL Editor.

-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  img TEXT, -- URL to the category icon/image
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Sub-Categories Table (Drug Classes)
CREATE TABLE IF NOT EXISTS subcategories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  img TEXT,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  image TEXT,
  gallery TEXT[],
  badge TEXT,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  subcategory_id BIGINT REFERENCES subcategories(id) ON DELETE SET NULL,
  variants JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create Animations Table (Hero Slider Banners)
CREATE TABLE IF NOT EXISTS animations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  subtitle TEXT,
  img TEXT,        -- Image URL
  is_delivery BOOLEAN DEFAULT FALSE, -- Flag for delivery-specific banners
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE animations ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies for Public Read Access (Drop if exists for idempotency)
DROP POLICY IF EXISTS "Public Read Categories" ON categories;
CREATE POLICY "Public Read Categories" ON categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Products" ON products;
CREATE POLICY "Public Read Products" ON products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Animations" ON animations;
CREATE POLICY "Public Read Animations" ON animations FOR SELECT USING (true);

-- 6. Create Policies for Admin Management (Write Access)
DROP POLICY IF EXISTS "Admin All Categories" ON categories;
CREATE POLICY "Admin All Categories" ON categories FOR ALL 
USING (auth.jwt()->>'email' = 'israelezrakisakye@gmail.com');

DROP POLICY IF EXISTS "Admin All Products" ON products;
CREATE POLICY "Admin All Products" ON products FOR ALL 
USING (auth.jwt()->>'email' = 'israelezrakisakye@gmail.com');

DROP POLICY IF EXISTS "Admin All Animations" ON animations;
CREATE POLICY "Admin All Animations" ON animations FOR ALL 
USING (auth.jwt()->>'email' = 'israelezrakisakye@gmail.com');

-- 7. Setup Storage Bucket for Image Uploads
INSERT INTO storage.buckets (id, name, public)
VALUES ('app_images', 'app_images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies (Drop if exists)
DROP POLICY IF EXISTS "Public Storage Read" ON storage.objects;
CREATE POLICY "Public Storage Read" ON storage.objects FOR SELECT
USING (bucket_id = 'app_images');

DROP POLICY IF EXISTS "Admin Storage Upload" ON storage.objects;
CREATE POLICY "Admin Storage Upload" ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'app_images' AND (auth.jwt()->>'email' = 'israelezrakisakye@gmail.com'));

DROP POLICY IF EXISTS "Admin Storage Manage" ON storage.objects;
CREATE POLICY "Admin Storage Manage" ON storage.objects FOR ALL
USING (bucket_id = 'app_images' AND (auth.jwt()->>'email' = 'israelezrakisakye@gmail.com'));

-- ==========================================
-- INITIAL DATA (Seed)
-- ==========================================

-- 1. Insert 10 Core Categories
INSERT INTO categories (name, img) VALUES 
('Drugs', 'https://i.pinimg.com/1200x/15/4f/6c/154f6c6318fc250236c54376d906f452.jpg'),
('Consumables', 'https://i.pinimg.com/1200x/de/14/de/de14de238d3b3aa763fba68c0d02db2a.jpg'),
('Surgical', 'https://images.unsplash.com/photo-1584622781564-1d9876a3e75d?auto=format&fit=crop&q=80&w=300'),
('Orthopedics', 'https://i.pinimg.com/1200x/a0/26/d7/a026d781617586521eb1809e29cb1764.jpg'),
('Laboratory', 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&q=80&w=300'),
('Diagnostics', 'https://i.pinimg.com/736x/dc/c7/36/dcc73645645065ebee4fba4297c7e937.jpg'),
('Dental', 'https://images.unsplash.com/photo-1588776814546-1ffce47267a5?auto=format&fit=crop&q=80&w=300'),
('Nursing', 'https://images.unsplash.com/photo-1576091160550-217359f49f4c?auto=format&fit=crop&q=80&w=300'),
('Radiology', 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=300'),
('Equipment', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=1200')
ON CONFLICT DO NOTHING;

-- 2. Insert 15 Essential Products
INSERT INTO products (name, description, price, image, badge, category_id) VALUES
('Premium Nitrile Gloves', 'Medical grade, powder-free blue nitrile gloves. AQL 1.5.', 45000, 'https://i.pinimg.com/1200x/de/14/de/de14de238d3b3aa763fba68c0d02db2a.jpg', 'Hot', 2),
('Digital Stethoscope V2', 'Crystal clear acoustic amplification for precise diagnostics.', 850000, 'https://i.pinimg.com/1200x/a0/26/d7/a026d781617586521eb1809e29cb1764.jpg', 'Trending', 6),
('Pulse Oximeter Pro', 'Fast and accurate SPO2 and heart rate readings.', 85000, 'https://i.pinimg.com/736x/dc/c7/36/dcc73645645065ebee4fba4297c7e937.jpg', 'New', 6),
('Surgical Face Masks (50pcs)', '3-Ply high filtration surgical masks with earloops.', 15000, 'https://i.pinimg.com/736x/dc/c7/36/dcc73645645065ebee4fba4297c7e937.jpg', 'Essential', 3),
('Sterile Syringes (2ml)', 'Single-use sterile syringes with ultra-sharp needles.', 35000, 'https://i.pinimg.com/1200x/de/14/de/de14de238d3b3aa763fba68c0d02db2a.jpg', 'Essential', 3),
('Infrared Thermometer', 'Professional non-contact laser thermometer for instant readings.', 125000, 'https://i.pinimg.com/1200x/a0/26/d7/a026d781617586521eb1809e29cb1764.jpg', 'Hot', 6),
('Blood Pressure Monitor', 'Automatic digital upper arm BP monitor with wide cuff.', 185000, 'https://i.pinimg.com/736x/dc/c7/36/dcc73645645065ebee4fba4297c7e937.jpg', 'Trending', 6),
('Glucometer Accu-Check', 'Reliable blood glucose monitoring system with 50 strips.', 145000, 'https://i.pinimg.com/1200x/de/14/de/de14de238d3b3aa763fba68c0d02db2a.jpg', 'Essential', 6),
('Adhesive Bandages', 'Flexible fabric bandages for wound protection.', 5000, 'https://i.pinimg.com/1200x/a0/26/d7/a026d781617586521eb1809e29cb1764.jpg', 'New', 2),
('Medical Alcohol 70%', 'High quality disinfecting spirit for medical surfaces.', 18000, 'https://i.pinimg.com/736x/dc/c7/36/dcc73645645065ebee4fba4297c7e937.jpg', 'Essential', 2),
('Gauze Rolls 5cm', 'Soft and absorbent cotton gauze for clinical dressing.', 25000, 'https://i.pinimg.com/1200x/de/14/de/de14de238d3b3aa763fba68c0d02db2a.jpg', 'New', 3),
('First Aid Kit Pro', 'Emergency medical kit containing all basic essentials.', 95000, 'https://i.pinimg.com/1200x/a0/26/d7/a026d781617586521eb1809e29cb1764.jpg', 'Trending', 2),
('N95 Dust Masks', 'High filtration N95 respirator masks, box of 10.', 45000, 'https://i.pinimg.com/736x/dc/c7/36/dcc73645645065ebee4fba4297c7e937.jpg', 'Hot', 3),
('Nebulizer Machine', 'Medical grade compressor nebulizer for respiratory therapy.', 215000, 'https://i.pinimg.com/1200x/de/14/de/de14de238d3b3aa763fba68c0d02db2a.jpg', 'New', 10),
('Oxygen Concentrator', '5 Liter hospital-grade oxygen supply machine.', 2850000, 'https://i.pinimg.com/1200x/a0/26/d7/a026d781617586521eb1809e29cb1764.jpg', 'Essential', 10);

-- 3. Insert Initial Animations
INSERT INTO animations (title, subtitle, img, is_delivery) VALUES
('Advanced Pharmaceutical Care', 'Your Trusted Partner in Health', 'https://i.pinimg.com/1200x/15/4f/6c/154f6c6318fc250236c54376d906f452.jpg', FALSE),
('Turbo Fast Delivery', 'Swift pharmaceutical delivery across Uganda within 24 hours.', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=1200', TRUE),
('Quality Lab Equipment', 'Precision tools for modern medical diagnostic centers.', 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&q=80&w=1200', FALSE)
ON CONFLICT DO NOTHING;
