-- Create Categories Table
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  img TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  image TEXT,
  badge TEXT,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Animations Table (Hero Banners)
CREATE TABLE animations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  subtitle TEXT,
  img TEXT,
  is_delivery BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert Initial Categories
INSERT INTO categories (name, img) VALUES
('Surgical', 'https://images.unsplash.com/photo-1584622781564-1d9876a3e75d?auto=format&fit=crop&q=80&w=300'),
('Diagnostic', 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&q=80&w=300');

-- Insert Initial Products
INSERT INTO products (name, description, price, image, badge, category_id) VALUES
('Premium Nitrile Gloves', 'AQL 1.5, Powder-Free, Blue', 45000, 'https://i.pinimg.com/1200x/de/14/de/de14de238d3b3aa763fba68c0d02db2a.jpg', 'Hot', 1),
('Digital Stethoscope V2', 'Ultra-precise acoustic amplification', 850000, 'https://i.pinimg.com/1200x/a0/26/d7/a026d781617586521eb1809e29cb1764.jpg', 'Trending', 2),
('Pulse Oximeter Pro', 'SPO2 & Heart Rate Monitoring', 85000, 'https://i.pinimg.com/736x/dc/c7/36/dcc73645645065ebee4fba4297c7e937.jpg', 'New', 2);

-- Insert 4 Animations (Hero Banners) - One for fast delivery
INSERT INTO animations (title, subtitle, img, is_delivery) VALUES
('Advanced Pharmaceutical Care', 'Your Trusted Partner in Health', 'https://i.pinimg.com/1200x/15/4f/6c/154f6c6318fc250236c54376d906f452.jpg', FALSE),
('Essential Medical Consumables', 'Quality Gloves & Kits for Every Facility', 'https://i.pinimg.com/1200x/de/14/de/de14de238d3b3aa763fba68c0d02db2a.jpg', FALSE),
('Turbo Fast Delivery', 'Swift pharmaceutical delivery across Uganda within 24 hours.', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=1200', TRUE),
('Premium Nursing Equipment', 'Excellence Driven Healthcare Solutions', 'https://i.pinimg.com/736x/dc/c7/36/dcc73645645065ebee4fba4297c7e937.jpg', FALSE);

-- Enable Row Level Security (RLS)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE animations ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access to categories" ON categories FOR SELECT USING (true);
CREATE POLICY "Allow public read access to products" ON products FOR SELECT USING (true);
CREATE POLICY "Allow public read access to animations" ON animations FOR SELECT USING (true);

-- Allow authenticated users to modify (admin logic on frontend checks israel email, but for true security you'd verify auth.jwt()->>'email' here)
CREATE POLICY "Allow admin write access to categories" ON categories FOR ALL USING (auth.jwt()->>'email' = 'israelezrakisakye@gmail.com');
CREATE POLICY "Allow admin write access to products" ON products FOR ALL USING (auth.jwt()->>'email' = 'israelezrakisakye@gmail.com');
CREATE POLICY "Allow admin write access to animations" ON animations FOR ALL USING (auth.jwt()->>'email' = 'israelezrakisakye@gmail.com');

-- -----------------------------------------------------
-- Storage Bucket for Image Uploads (Gallery integration)
-- -----------------------------------------------------

-- Create a public bucket called 'app_images'
INSERT INTO storage.buckets (id, name, public)
VALUES ('app_images', 'app_images', true)
ON CONFLICT (id) DO NOTHING;

-- Allow public read access to the app_images bucket
CREATE POLICY "Public Image Read" ON storage.objects FOR SELECT
USING (bucket_id = 'app_images');

-- Allow authenticated users (Admins) to upload images directly
CREATE POLICY "Admin Image Upload" ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'app_images' AND auth.role() = 'authenticated');
